const apps={
  projects:{title:'Projects.app',body:`<h3>Selected work</h3><p>Products built from concept to deployed experience.</p><article class="project"><h4>Ora Jewellers</h4><span class="tag">Full development</span><span class="tag">Jewellery</span><span class="tag">Responsive web</span><p>A complete jewellery website experience, developed end to end with a refined product presentation and a customer-facing browsing flow.</p><a href="https://orajweles.lovable.app/" target="_blank" rel="noreferrer noopener">Visit project ↗</a></article><article class="project"><h4>3D Interactive Website</h4><span class="tag">3D web</span><span class="tag">Interactive UI</span><span class="tag">Recorded demo</span><p>An experimental interactive 3D web experience. The project is complete; a screen recording is available while its public deployment is pending.</p><video class="project-video" controls preload="metadata"><source src="assets/videos/3d-interactive-website-demo.mp4" type="video/mp4" />Your browser does not support this video.</video><span class="tag">Not publicly deployed</span></article><article class="project"><h4>Mahalaxmi Jewellers</h4><span class="tag">MERN</span><span class="tag">E-commerce</span><span class="tag">Real-time catalog</span><p>Full-stack jewellery e-commerce experience with category filtering, authentication, cart, product detail pages, multiple checkout options, responsive motion, and WhatsApp click-to-chat.</p><a href="https://mahalaxmi-jwellers-owb2-ivory.vercel.app/" target="_blank" rel="noreferrer noopener">Visit live site ↗</a></article><article class="project"><h4>SmartChef</h4><span class="tag">AI integration</span><span class="tag">REST APIs</span><p>AI-driven recipe recommendations shaped by mood, dietary preferences, and available ingredients to suggest personalised meals in real time.</p></article><article class="project"><h4>StudyMentor</h4><span class="tag">SaaS</span><span class="tag">AI mentorship</span><p>AI-powered study-planning product with adaptive learning logic that adjusts content difficulty and pacing around individual progress.</p></article>`},
  skills:{title:'Skills.app',body:`<h3>Technical toolkit</h3><p>Comfortable moving across product, interface, API, data, and deployment work.</p><div class="skill-list">${['JavaScript (ES6+)','React.js','Next.js','Node.js','Express.js','MongoDB','Mongoose ODM','REST APIs','Tailwind CSS','HTML5','CSS3','Python','C++','NumPy','Pandas','GCP','AWS Gen AI','Git & GitHub'].map(x=>`<span class="tag">${x}</span>`).join('')}</div><h3 style="margin-top:30px">Learning direction</h3><p>Machine-learning fundamentals, cloud-native development, and practical AI systems.</p>`},
  proof:{title:'Proof.app',body:`<h3>What I bring</h3><div class="project"><h4>End-to-end product thinking</h4><p>From early idea through polished, deployed, user-facing web applications.</p></div><div class="project"><h4>Data-aware decisions</h4><p>Google Data Analytics training informs feature choices and UX iteration.</p></div><div class="project"><h4>Practical AI integration</h4><p>Building AI-enabled product experiences without losing sight of usability and scale.</p></div><div class="project"><h4>Cloud foundations</h4><p>Training across Google Cloud and AWS Generative AI, alongside hands-on development practice.</p></div><p><small>Claims based on Rohan Hiremathswami’s supplied résumé; no unverified user-growth metric is shown.</small></p>`},
  founder:{title:'Founder.txt',body:`<h3>Building in public, learning in depth.</h3><p>I’m Rohan Hiremathswami, a BCA Computer Science student and full-stack developer from Kolhapur. I build web products that combine strong product thinking with modern web engineering.</p><p>My work spans AI-powered SaaS concepts, e-commerce experiences, and interactive applications built with the MERN stack. I’m currently deepening my machine-learning and cloud knowledge while seeking internships and collaborative projects where I can contribute real value.</p><p><a href="https://www.linkedin.com/in/rohan-hiremathswami" target="_blank" rel="noreferrer noopener">Connect on LinkedIn ↗</a></p>`},
  whiteboard:{title:'Whiteboard.app',body:`<h3>Leave a note</h3><p>Stored only in this browser on this device.</p><form class="note-form" id="noteForm"><input id="noteInput" maxlength="160" required placeholder="A project idea, collaboration note, or hello…" aria-label="New note" /><button>Add note</button></form><ul class="notes" id="notes"></ul>`}
};
const layer=document.querySelector('#windowLayer'),template=document.querySelector('#windowTemplate');
function openApp(key){const app=apps[key];if(!app)return;layer.innerHTML='';const node=template.content.cloneNode(true);node.querySelector('h2').textContent=app.title;node.querySelector('.window-body').innerHTML=app.body;node.querySelector('.close').addEventListener('click',closeApp);layer.append(node);layer.classList.add('active');node.querySelector('.close').focus();if(key==='whiteboard')setupNotes()}
function closeApp(){layer.classList.remove('active');layer.innerHTML=''}
document.addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)openApp(b.dataset.open);if(e.target===layer)closeApp()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeApp()});
const clock=document.querySelector('#clock');function tick(){clock.textContent=new Intl.DateTimeFormat('en-IN',{hour:'2-digit',minute:'2-digit',hour12:true,timeZone:'Asia/Kolkata'}).format(new Date())+' IST'}tick();setInterval(tick,30000);
document.querySelector('#themeToggle').addEventListener('click',()=>{document.body.classList.toggle('night');localStorage.setItem('rohan-os-theme-v1',document.body.classList.contains('night')?'night':'day')});if(localStorage.getItem('rohan-os-theme-v1')==='night')document.body.classList.add('night');
function setupNotes(){const list=document.querySelector('#notes'),input=document.querySelector('#noteInput'),form=document.querySelector('#noteForm');let notes=[];try{notes=JSON.parse(localStorage.getItem('rohan-os-whiteboard-v1')||'[]')}catch{}const render=()=>list.innerHTML=notes.map((n,i)=>`<li>${escapeHtml(n)} <button aria-label="Delete note" data-delete="${i}">×</button></li>`).join('');form.addEventListener('submit',e=>{e.preventDefault();notes.unshift(input.value.trim());localStorage.setItem('rohan-os-whiteboard-v1',JSON.stringify(notes));input.value='';render()});list.addEventListener('click',e=>{const i=e.target.dataset.delete;if(i!==undefined){notes.splice(i,1);localStorage.setItem('rohan-os-whiteboard-v1',JSON.stringify(notes));render()}});render()}
function escapeHtml(value){const d=document.createElement('div');d.textContent=value;return d.innerHTML}
